export const FETCH_USERS = "FETCH_USERS";
export const FETCH_GENDER = "FETCH_GENDER";
export const FETCH_SEARCHED = "FETCH_SEARCHED";
export const FETCH_PAGINATION = "FETCH_PAGINATION";
export const UPDATE_SORTING = "UPDATE_SORTING";
